### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by martindotlindner** [offenesdresden/themenstadtscraper#1]
Hello,
Many thanks for writing this great tool. The 'Themenstadtplan' offers a great amount of data. I tried to use your code, but got this error: 

`Traceback (most recent call last):
  File "themenstadtscraper.py", line 89, in <module>
    scrape()
  File "themenstadtscraper.py", line 83, in scrape
    handle_json_response(res.json(), pg_cursor)
  File "themenstadtscraper.py", line 31, in handle_json_response
    lat = response_data["value"]["PointInWgs"]["Y"]
KeyError: 'value'`

Any suggestion to avoid this problem? Many thanks for reply!

**Comment by thomersch** [comment]
Hi Martin!
It seems that they have changed their API and the code doesn't work anymore. The code is a big, bad hack anyway, because it simulates what happens if you click the map. So anyway you would only get point data and no proper geometries. Probably we could try to change the code to the new responses, but honestly I am not sure if this is worth it.

There is a lot more published open data nowadays, so maybe check out https://www.opendata.sachsen.de and http://www.dresden.de/de/wirtschaft/wirtschaftsstandort/projekte-kooperationen/open-data-crunch.php if you are looking for data.

Thomas
